example_bins: Disk Class Reference
Disk Class Reference
Public Member Functions
Disk ()
int freeSpace ()
void add (int filesize)
String toString ()
boolean equals (Object other)
int compareTo (Disk other)
Static Public Member Functions
static void reset ()
Static Public Attributes
static final int MAX_CAPACITY = 1000000
Private Attributes
int myId
int mySize
int myCapacity
List< Integer > myFiles
Static Private Attributes
static int ourId = 0
Detailed Description
Represents a collection of files; how many it can hold is limited by its capacity.
Definition at line 8 of file Disk.java.
Constructor & Destructor Documentation
Disk.Disk ()
Create an empty Disk.
Definition at line 28 of file Disk.java.
References MAX_CAPACITY.
Referenced by equals().
Member Function Documentation
void Disk.add (int filesize)
Adds the given file to this disk.
No error checking is done to ensure the file can fit on this disk.
Parameters
filesize size of file to add to this disk
Definition at line 49 of file Disk.java.
Referenced by Algorithm.addFiles().
int Disk.compareTo (Disk other)
Compare this disk's information to the given disk's for ordering.
Note, currently only equality is based only on their free space.
Parameters
other disk to compare to this disk
Returns
positive if this disk is greater than the given disk, zero if they are equal, and negative if this disk is less than the given disk
Definition at line 89 of file Disk.java.
References freeSpace(), and myId.
boolean Disk.equals (Object other)
Check if this disk's information is the same as the given disk's.
Note, currently only equality is based only on their ID.
Parameters
other disk to compare to this disk
Returns
true iff their values match
Definition at line 75 of file Disk.java.
References Disk(), and myId.
int Disk.freeSpace ()
Returns
amount of free space available on this disk
Definition at line 38 of file Disk.java.
References mySize.
Referenced by Algorithm.addFiles(), compareTo(), and toString().
static void Disk.reset () static
Reset Disk's ID numbering algorithm.
Definition at line 20 of file Disk.java.
String Disk.toString ()
Converts this disk's information to a string.
Definition at line 58 of file Disk.java.
References freeSpace().
Member Data Documentation
final int Disk.MAX_CAPACITY = 1000000 static
Definition at line 9 of file Disk.java.
Referenced by Disk().
int Disk.myCapacity private
Definition at line 13 of file Disk.java.
List<Integer> Disk.myFiles private
Definition at line 14 of file Disk.java.
int Disk.myId private
Definition at line 11 of file Disk.java.
Referenced by compareTo(), and equals().
int Disk.mySize private
Definition at line 12 of file Disk.java.
Referenced by freeSpace().
int Disk.ourId = 0 static private
Definition at line 10 of file Disk.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_bins/repository/src/Disk.java