example_bins: Algorithm Class Reference
Algorithm Class Reference abstract
Public Member Functions
Algorithm (String description)
void fitDisksAndPrint (List< Integer > data)
Protected Member Functions
abstract void organizeData (List< Integer > data)
Private Member Functions
Collection< Disk > addFiles (List< Integer > data)
void printResults (Collection< Disk > disks, String description)
Private Attributes
String myDescription
Detailed Description
This class represents worst-fit algorithms for allocating files to disks.
Author
rcd
Definition at line 12 of file Algorithm.java.
Constructor & Destructor Documentation
Algorithm.Algorithm (String description)
Create with given descriptor.
Definition at line 19 of file Algorithm.java.
Member Function Documentation
Collection<Disk> Algorithm.addFiles (List< Integer > data) private
Definition at line 44 of file Algorithm.java.
References Disk.add(), and Disk.freeSpace().
Referenced by fitDisksAndPrint().
void Algorithm.fitDisksAndPrint (List< Integer > data)
Allocates given files to the fewest number of disks.
Parameters
data collection of files to be allocated to disks
Definition at line 28 of file Algorithm.java.
References addFiles(), organizeData(), and printResults().
abstract void Algorithm.organizeData (List< Integer > data) abstract protected
Arrange given data in preparation for fitting disks.
Parameters
disks collection of disks to be printed
Referenced by fitDisksAndPrint().
void Algorithm.printResults (Collection< Disk > disks, String description) private
Definition at line 65 of file Algorithm.java.
Referenced by fitDisksAndPrint().
Member Data Documentation
String Algorithm.myDescription private
Definition at line 13 of file Algorithm.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_bins/repository/src/Algorithm.java