example_bins: Bins Class Reference
Bins Class Reference
Public Member Functions
List< Integer > readData (Scanner input)
int getTotal (Collection< Integer > data)
Static Public Member Functions
static void main (String args[])
Static Private Attributes
static Algorithm algortihmsToCompare []
Detailed Description
Runs a number of algorithms that try to fit files onto disks.
Definition at line 11 of file Bins.java.
Member Function Documentation
int Bins.getTotal (Collection< Integer > data)
Returns sum of all values in given list.
Definition at line 36 of file Bins.java.
Referenced by main().
static void Bins.main (String args[]) static
The main program.
Definition at line 47 of file Bins.java.
References getTotal(), and readData().
List<Integer> Bins.readData (Scanner input)
Reads list of integer data from the given input.
Parameters
input tied to an input source that contains space separated numbers
Returns
list of the numbers in the order they were read
Definition at line 25 of file Bins.java.
Referenced by main().
Member Data Documentation
Algorithm Bins.algortihmsToCompare[] static private
Initial value:
= {
        new WorstFitAlgorithm(),
        new WorstFitDecreasingAlgorithm()
    }
Definition at line 13 of file Bins.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_bins/repository/src/Bins.java